name: Deploy DM APP

on:
  repository_dispatch:
    types: [update-dm-api]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout infra repository
        uses: actions/checkout@v3

      - name: Config AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Apply Terraform 
        run: |
          cd terraform/modules/ec2
          terraform init
          terraform import aws_instance.dm_ec2 i-0476fdd7b1fdb05a6
          terraform plan -var="subnet_id=${{ secrets.SUBNET_ID }}" -var="vpc_id=${{ secrets.VPC_ID }}" -var="key_name=${{ secrets.KEY_NAME }}"
          terraform apply

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Deploy NestJS SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d "/home/ubuntu/app" ]; then
              git clone https://github.com/hilton98/device-management-api.git app
            else
              cd app
              git pull origin main
            fi

            cd /home/ubuntu/app

            # Instalar dependências
            npm install
            npm run build

            sudo npm install -g pm2
            pm2 start dist/main.js --name nest-backend || pm2 restart nest-backend
