name: Deploy DM API

on:
  repository_dispatch:
    types: [deploy-dm-api]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            pm2 delete dm-api || true
            git pull origin main
            npm install
            npm run build
            npm run migration:run
            pm2 start dist/main.js --name dm-api
